### ISSUE TITLE
Add bootstrap script

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/TraceR#1]
@bhatele -- you might want to consider creating a bootstrap script that would handle grabbing and installing all of the various dependencies. I'd be happy to polish something, not at a terminal to try creating it myself at the moment though.

**Comment by bhatele** [comment]
Both for TraceR and Chizu, which I am going to add next, the plan is to add spack packages. If that is something you want to try, it would be a lot of help.

**Comment by bhatele** [comment]
We now have spack packages for ROSS, CODES and TraceR
